---

- name: Create unbound group
  ansible.builtin.group:
    name: unbound
    state: present

- name: Create unbound user (nologin shell)
  ansible.builtin.user:
    name: unbound
    group: unbound
    state: present
    system: yes
    shell: /usr/sbin/nologin

- name: Create unbound configuration folder
  file: 
    path: /etc/unbound/conf.d
    state: directory
    owner: unbound
    mode: 0755
  notify: restart

- name: Create unbound configuration files
  template:
     src: "{{ item }}.j2"
     dest: "/etc/unbound/conf.d/{{ item }}"
     owner: unbound
  with_items:
     - 01_general.conf
  notify: restart

- name: Retreive unbound configuration files
  find: 
    paths: /etc/unbound/conf.d
  register: unbound_conf_list
  check_mode: no

- name: Create unbound.conf to include all configuration
  template:
     src: "unbound.conf.j2"
     dest: "/etc/unbound/unbound.conf"
     owner: unbound
     validate: "/usr/sbin/unbound-checkconf %s"
  notify: restart
